[package]
name = "slipstream-feeds"
description = "Feed fetching, filtering, and aggregating utilities."
version = "0.13.4"
edition.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
rust-version.workspace = true

[dependencies]
chrono = { workspace = true }
htmd = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }

atom_syndication = { workspace = true }
rss = "2.0"

async-trait = "0.1"
downcast-rs = "2.0.1"
serde_json = "1.0"

[dev-dependencies]
tracing-subscriber = { workspace = true }
