# slipstream example config

# Root settings for the updater.
freq = "5min"
cache = "2min"
database = "slip.db"

# Settings that apply to **everything**.
[global]

[global.filters]
exclude-title-words = [
  "llm",
]
exclude-content-words = [
  "javascript",
  "node",
  "nodejs",
]

[global.options]
# Maximum feeds returned, something sane.
max = 512
# Oldest entry stored.
oldest = "1month"

# Settings that apply to the all feed.
[all]

[all.filters]
exclude-title-words = [
  "release",
]
exclude-tags = ["rust"]

# Feed definitions.
[feeds]

[feeds.hacking]
feeds = ["rust-blog", "hachha-hacking"]

[feeds.local]
url = "https://127.0.0.1:3000/all/feed"
tags = ["local"]
max = 20

[feeds.rust-blog]
url = "https://blog.rust-lang.org/feed.xml"
tags = ["blog", "rust", "tech"]
max = 5

[feeds.hachha-hacking]
url = "https://feeds.hachha.dev/tag/hacking/feed"
tags = ["hacking", "tech"]
max = 10

[feeds.hachha]
url = "https://hachha.dev/blog.feed"
tags = ["hacking", "tech"]

[feeds.shimbun-science]
url = "https://www.asahi.com/rss/asahi/science.rdf"
tags = ["science"]

[feeds.shimbun-env]
url = "https://www.asahi.com/rss/asahi/eco.rdf"
tags = ["environment", "energy"]

[read]
scroll = 1

[read.tags]
hidden = ["unread"]

[[read.tags.colors]]
tag = "important"
color = { bg = "red", fg = "black" }

[[read.tags.colors]]
tag = "unread"
color = { fg = "yellow" }

[[read.tags.colors]]
tag = "hacking"
color = { underline = "light-cyan" }

[read.hooks]
fetch = []
insert = [":add-tag unread"]
read = [":remove-tag unread"]

[read.bindings]
i = ":toggle-tag important"
a = ":toggle-tag archive"
r = "!read"
C-a = "!archive"
o = "!open"
S-o = "!open-2"
u = "update"
C-d = "page-down"
C-u = "page-up"

1 = "!read-1"
C-1 = "!archive-1"
S-1 = "!open-1"
2 = "!read-2"
C-2 = "!archive-2"
S-2 = "!open-2"
3 = "!read-3"
C-3 = "!archive-3"
S-3 = "!open-3"
4 = "!read-4"
C-4 = "!archive-4"
S-4 = "!open-4"

# Read the url.
[[read.commands]]
name = "read"
command = [
  "fish",
  "-c",
  """
  curl \
    --silent \
    -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36" \
    {{link.url}} \
  | pandoc \
    --from html \
    --to gfm-raw_html \
    -o - \
  | bat \
    --color=always \
    --language=markdown \
    --terminal-width={{terminal.width}} \
    -
  """
]

[[read.commands]]
name = "read-1"
command = ["fish", "-c", "curl --silent -A \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36\" {{link.url1}} | pandoc --from html --to gfm-raw_html -o - | bat --color=always --language=markdown --terminal-width={{terminal.width}} -"]
[[read.commands]]
name = "read-2"
command = ["fish", "-c", "curl --silent -A \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36\" {{link.url2}} | pandoc --from html --to gfm-raw_html -o - | bat --color=always --language=markdown --terminal-width={{terminal.width}} -"]
[[read.commands]]
name = "read-3"
command = ["fish", "-c", "curl --silent -A \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36\" {{link.url3}} | pandoc --from html --to gfm-raw_html -o - | bat --color=always --language=markdown --terminal-width={{terminal.width}} -"]
[[read.commands]]
name = "read-4"
command = ["fish", "-c", "curl --silent -A \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36\" {{link.url4}} | pandoc --from html --to gfm-raw_html -o - | bat --color=always --language=markdown --terminal-width={{terminal.width}} -"]

# Open the url.
[[read.commands]]
name = "open"
command = ["fish", "-c", "xdg-open {{link.url}}"]

[[read.commands]]
name = "open-1"
command = ["fish", "-c", "xdg-open {{link.url1}}"]
[[read.commands]]
name = "open-2"
command = ["fish", "-c", "xdg-open {{link.url2}}"]
[[read.commands]]
name = "open-3"
command = ["fish", "-c", "xdg-open {{link.url3}}"]
[[read.commands]]
name = "open-4"
command = ["fish", "-c", "xdg-open {{link.url4}}"]

# Archive.
[[read.commands]]
name = "archive"
command = [
  "fish",
  "-c",
  """
    monolith \
      --no-js \
      --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36" \
      --output ~/media/articles/{{link.name-}}.html \
      {{link.url}}
  """,
]

[[read.commands]]
name = "archive-1"
command = ["fish", "-c", """monolith --no-js --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36" --output ~/media/articles/{{link.name-}}.html {{link.url1}}""",]
[[read.commands]]
name = "archive-2"
command = ["fish", "-c", """monolith --no-js --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36" --output ~/media/articles/{{link.name-}}.html {{link.url2}}""",]
[[read.commands]]
name = "archive-3"
command = ["fish", "-c", """monolith --no-js --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36" --output ~/media/articles/{{link.name-}}.html {{link.url3}}""",]
[[read.commands]]
name = "archive-4"
command = ["fish", "-c", """monolith --no-js --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36" --output ~/media/articles/{{link.name-}}.html {{link.url4}}""",]

