# slipstream example config

# Root settings for the updater.
freq = "5min"
cache = "2min"

# Settings that apply to **everything**.
[global]

[global.filters]
exclude-title-words = [
  "llm",
]
exclude-content-words = [
  "javascript",
  "node",
  "nodejs",
]

[global.options]
# Maximum feeds returned, something sane.
max = 512
# Oldest entry stored.
oldest = "1month"

# Settings that apply to the all feed.
[all]

[all.filters]
exclude-title-words = [
  "release",
]
exclude-tags = ["rust"]

# Feed definitions.
[feeds]

[feeds.hacking]
feeds = ["rust-blog", "hachha-hacking"]

[feeds.rust-blog]
url = "https://blog.rust-lang.org/feed.xml"
tags = ["blog", "rust", "tech"]
max = 5

[feeds.hachha-hacking]
url = "https://feeds.hachha.dev/tag/hacking/feed"
tags = ["hacking", "tech"]
max = 10

# [feeds.hachha]
# url = "https://hachha.dev/blog.feed"
# tags = ["hacking", "tech"]
