# slipstream example config

# Root settings for the updater.
freq = "5min"

# Settings that apply to **everything**.
[global]
user-agent = "slipstream/2.0"

[global.filters]
exclude-title-words = [
  "llm",
]
exclude-content-words = [
  "javascript",
  "node",
  "nodejs",
]

[global.options]
# Maximum feeds returned, something sane.
max = 512
# Oldest entry stored.
oldest = "1month"

# Serve options.
[serve]
port = 3000
show_source_in_title = true
cache = "2min"

# Settings that apply to the all feed.
[serve.all]

[serve.all.filters]
exclude-title-words = [
  "release",
]
exclude-tags = ["satire"]

# Feed definitions.
[feeds]

[feeds.hacking]
feeds = ["hackernews", "ziglang-compilation"]

[feeds.hackernews]
url = "https://news.ycombinator.com/rss"
tags = ["tech", "news"]
exclude-title-words = ["llm", "hiring"]
freq = "1hr"

[feeds.ziglang-compilation]
url = "https://ziglang.org/devlog/index.xml"
tags = ["blog", "zig", "tech"]
include-substrings = ["llvm", "compilation", "binary", "optimization"]

[feeds.nhk]
url = "https://www3.nhk.or.jp/rss/news/cat0.xml"
tags = ["news", "japanese"]
max = 5
