[package]
name = "slipstream"
description = "UI for `slipstream`, backed by `slipstore`."
version = "0.1.0"
# authors = ["hachha <hachha@hachha.dev>"]
edition = "2021"

[dependencies]
dioxus = { version = "0.5.6", features = ["web", "router"] }
dioxus-logger = "0.5.1"
rusqlite = { version = "0.32.0", features = ["bundled"] }
regex = "1.10.6"

slipfeed = { path = "../slipfeed" }
